### ISSUE TITLE
Build issues on Debian 10

### ISSUE THREAD

**Issue by bradclawsie** [croservices/cro#100]
Problems building Cro on a new moarvm (branch `master`) on Debian 10
 
```
$ perl6 --version
This is Rakudo version 2019.07.1-237-g0455f42e3 built on MoarVM version 2019.07.1-134-ga37504d12
implementing Perl 6.d.
$ zef install --/test --force-install cro
===> Searching for: cro
===> Installing: cro:ver<0.8.1>
===> Install [FAIL] for cro:ver<0.8.1>: ===SORRY!=== Error while compiling /home/brad/site#sources/ADB31520994572F18CE4EC4457E5E9321A31301C (YAMLish)
Class YAMLish::Grammar cannot inherit from itself
at /home/brad/site#sources/ADB31520994572F18CE4EC4457E5E9321A31301C (YAMLish):152

===SORRY!=== Error while compiling /home/brad/site#sources/ADB31520994572F18CE4EC4457E5E9321A31301C (YAMLish)
Class YAMLish::Grammar cannot inherit from itself
at /home/brad/site#sources/ADB31520994572F18CE4EC4457E5E9321A31301C (YAMLish):152
```

**Comment by bradclawsie** [comment]
This works fine if I use `2019.07.1`...I don't know what the official policy is regarding the stability of `master` (maybe only the dated releases are expected to be stable)...but it seems more prudent to close this

**Comment by jnthn** [comment]
This looks like a regression in Rakudo HEAD that breaks a Cro dependency; it's already been caught by blin (the pre-release testing), so will certainly be addressed before the next release. (With regard to stability of master: of course nobody breaks things for the fun of it, but sometimes breakage happens.)
