### ISSUE TITLE
MoarVM requests extra 4.5 GB's after making a request to a cro based server

### ISSUE THREAD

**Issue by davidholoshka** [croservices/cro#104]
The server code only manipulates a few KB of data at the most for each request; getting a document from elasticsearch using www  to do a get and a row from a mariaDB db using DBIish.  Is this expected behavior for the VM ?  The o/s monitor shows perl6 with 4 G's allocated.

**Comment by jnthn** [comment]
> Is this expected behavior for the VM ?

Well, only if it's being asked to do that.

> from a mariaDB db using DBIish

I wonder if it could be [this issue](https://github.com/perl6/DBIish/issues/74)?

**Comment by davidholoshka** [comment]
Hi,

Yes it was DBIish allocating for a longtext field even though it is 
defined as 64k.  Thank you for the tip.  Should I close the issue ?

Best Regards,

David

**Comment by jnthn** [comment]
Thanks for replying; glad my wild guess was actually somewhat useful! :-) Yes, since there's already an issue against DBIish, and nothing we could really do about it in Cro, I think this can be closed.
