### ISSUE TITLE
`cro stub http` generates invalid Dockerfile

### ISSUE THREAD

**Issue by Altreus** [croservices/cro#107]
The Dockerfile it created chose `croservices/cro-http:0.8.2` as a base, but this doesn't exist.

Presumably it assumes that there is a docker image on dockerhub for the current version of Cro, but this is apparently not guaranteed.

Would it make sense just to use `latest`?

**Comment by jnthn** [comment]
> Presumably it assumes that there is a docker image on dockerhub for the current version of Cro, but this is apparently not guaranteed.

Ah, yes, something went wrong with producing those this time. It's resolved now.

> Would it make sense just to use latest?

No.

**Comment by jnthn** [comment]
> No.

Ah, and I should have said why: because much of the value in containers is that, in principle, stuff that works keeps working, and `latest` works against that.
