### ISSUE TITLE
middleware reference link is dead - may be cut&paste'o

### ISSUE THREAD

**Issue by finanalyst** [croservices/cro#113]
In the documentation on 'Cro::HTTP::Router' in the section on middleware, there is a link associated with the words 'the HTTP middleware guide gives an overview'. The link is dead (or at least generates a blank http page).

The link is `https://cro.services/docs/reference/docs/reference/cro-http-middleware`

There is a file `cro.services/docs/reference/cro-http-middleware.md`

So it's possible this is a cut-paste error.

**Comment by jnthn** [comment]
This is fixed after the website/docs update of the latest release; thanks for reporting.
