### ISSUE TITLE
cro run should inform there is no .cro.yml around

### ISSUE THREAD

**Issue by Altai-man** [croservices/cro#115]
Currently, if you run `cro run .` in a directory with no .cro.yml file, it'll start and... no output, so you have no idea if (pre)compilation times have exploded or what.

I think it will be less misleading for the user to print a message, something like "No .cro.yml files in this directory found, awaiting..." after 5 seconds of waiting.

**Comment by jnthn** [comment]
Nitpick: it actually scans subdirectories too. But yes, in general, agree we should give such a warning.

**Comment by Altai-man** [comment]
>it actually scans subdirectories too
Well, if it did scan everything and no `.cro.yml` found...
