### ISSUE TITLE
Docker-hub missing Cro-http:0.8.3

### ISSUE THREAD

**Issue by josemanimala** [croservices/cro#116]
```
docker build -t service .
Sending build context to Docker daemon  99.84kB
Step 1/8 : FROM croservices/cro-http:0.8.3
manifest for croservices/cro-http:0.8.3 not found: manifest unknown: manifest unknown
```

**Comment by josemanimala** [comment]
@jnthn 
> If you could add documentation on how to build/ changes needed to build the docker base images, I could raise a PR with the necessary changes.

**Comment by jnthn** [comment]
Not docs exactly, but there's [a repository with the images](https://github.com/croservices/docker) and it's mostly a scripted process (except deciding to update the Rakudo base images). I've already run it and pushed the latest images; sorry for the delay on that.

**Comment by josemanimala** [comment]
Thank you. @jnthn
