### ISSUE TITLE
Cro for dummies

### ISSUE THREAD

**Issue by kaicarver** [croservices/cro#13]
Cro looks awesome, and the documentation is pretty nice, but I could have used a a simple one-stop tutorial for how to get up and running, a page with something like the following (to be detailed)

1. Install Perl 6 (link to site and instructions) and zef (saying what that is)

2. Install Cro (using zef)

3. Hello World server app example source code

4. How to run the Hello server app

5. How to test that it works: localhost:10000, localhost:100000/greet/YourName

You're done! 

Extra credit:

6. Use "cro run" to run the service in a smarter way, that auto-reloads when you modify the file (haven't tried this yet)

If you think this would be useful but don't want to write this, I could take a shot at it and submit it to you. Let me know.

-- a dummy

**Comment by jnthn** [comment]
Thanks for the feedback! We have a page [here](http://cro.services/docs/intro/http-server) that goes through some of that; I think it would be best to improve that in the ways you suggest, rather than add an entirely new article.

**Comment by kaicarver** [comment]
OK I'll see what I can do. 

(Still, in my humble opinion a separate page helping people get up and running quickly would be nice,, since basic sysadmin plumbing issues of installing and running Cro are quite different from learning how to use it.

For example, I was quite happy to get things working on Ubuntu, and knowing that made me want to play with more advanced examples. However, since then I have been on a Windows PC, and I failed three different ways to get Cro working (native, Cygwin, and Ubuntu bash shell, in a variety of mysterious and boring ways). I guess a VM will be my next try when I'm not using the Ubuntu PC.

For people like me "getting things running" is a non-trivial step. I had installed Perl 6 several times in the distant past, but of course had to figure out how to install it all over again to have the latest version on my current platform(s). Others may know even less than me if they were just attracted by the clever way of doing micro services, and know nothing about Perl or Perl 6. For such people, "Just zef install --/test cro and check out the documentation" is imho currently too terse.  They could use a friendlier introduction to Prl 6 and how to run a Cro program.)

**Comment by jnthn** [comment]
Fair point on a separate page; I guess let's do it that way, put it up front as "Installing Cro" or some such, and then link to it from the other pages ("first install Cro", etc.)

**Comment by kaicarver** [comment]
ok! will try to get to that before this weekend

**Comment by kaicarver** [comment]
Here's a pull request for that, hope it helps. 
https://github.com/croservices/cro/pull/17

The stub part is not tested as I couldn't fully get stub and run working, but maybe can leave it in with a note saying it may not work on all platforms yet.

Let me know if you want me to change anything. And if you're too busy to deal with this now that's ok too I understand, it's not very important :-)

**Comment by Altai-man** [comment]
@kaicarver, the PR is merged, do you think that the issue can be closed?

**Comment by kaicarver** [comment]
Ah right. The updated documentation is not on the web site yet, but I guess it will get there. 

Closing, and thanks!
