### ISSUE TITLE
installation cro http windows.

### ISSUE THREAD

**Issue by jaffa4** [croservices/cro#141]
zef install Cro::HTTP
===> Searching for: Cro::HTTP
===> Searching for missing dependencies: IO::Socket::Async::SSL, OO::Monitors, IO::Path::ChildSecure, Base64, HTTP::HPACK, Cro::TLS:ver<0.8.7>, Crypt::Random, JSON::JWT, DateTime::Parse, Log::Timeline
===> Searching for missing dependencies: if, CBOR::Simple, MIME::Base64, OpenSSL, Digest::HMAC
===> Searching for missing dependencies: Digest, PathTools, TinyFloats:ver<0.0.3+>
===> Building: OpenSSL:ver<0.1.28>
===> Building [OK] for OpenSSL:ver<0.1.28>
===> Testing: PathTools:ver<0.1.1>:auth<github:ugexe>
===> Testing [OK] for PathTools:ver<0.1.1>:auth<github:ugexe>
===> Testing: OpenSSL:ver<0.1.28>
[OpenSSL] # NETWORK_TESTING was not set
[OpenSSL] # NETWORK_TESTING was not set
===> Testing [OK] for OpenSSL:ver<0.1.28>
===> Testing: IO::Socket::Async::SSL:ver<0.7.9>:auth<jnthn>
===> Testing [OK] for IO::Socket::Async::SSL:ver<0.7.9>:auth<jnthn>
===> Testing: OO::Monitors:ver<1.1.1>
===> Testing [OK] for OO::Monitors:ver<1.1.1>
===> Testing: IO::Path::ChildSecure:ver<1.001011>
[IO::Path::ChildSecure]     # Failed test 'code returned a Failure'
[IO::Path::ChildSecure]     # at t\01-operation.t line 50
[IO::Path::ChildSecure]     # Actual type: IO::Path
[IO::Path::ChildSecure]         # Failed test 'code dies'
[IO::Path::ChildSecure]         # at t\01-operation.t line 51
[IO::Path::ChildSecure]         # You failed 1 test of 2
[IO::Path::ChildSecure]     # Failed test 'Failure threw when sunk'
[IO::Path::ChildSecure]     # at t\01-operation.t line 51
[IO::Path::ChildSecure]     # You failed 2 tests of 2
[IO::Path::ChildSecure] # Failed test 'resolved parent fails (given path is not a child, via combiners)'
[IO::Path::ChildSecure] # at t\01-operation.t line 40
[IO::Path::ChildSecure] # You failed 1 test of 10
===> Testing [FAIL]: IO::Path::ChildSecure:ver<1.001011>
Aborting due to test failure: IO::Path::ChildSecure:ver<1.001011> (use --force-test to override)

**Comment by jnthn** [comment]
This is not a problem with this module, but rather in the dependency `IO::Path::ChildSecure`, and [there is already a bug report for that](https://github.com/raku-community-modules/IO-Path-ChildSecure/issues/3).

**Comment by jaffa4** [comment]
Yes, but this module is useless...without that , right? Can you use another module?

**Comment by jaffa4** [comment]
DId you look at the dates? THat modules has not been updated for ages.

**Comment by jaffa4** [comment]
That bug report almost 11 months... Did this calm you down? When will it be fixed if it has not been fixed in 11 months?

**Comment by coke** [comment]
Bug in the test itself, fixed by https://github.com/raku-community-modules/IO-Path-ChildSecure/pull/4
