### ISSUE TITLE
rename SSL to TLS

### ISSUE THREAD

**Issue by abraxxa** [croservices/cro#18]
Because SSL up to version 3.0 is already deprecated by RFC7568 I'd suggest renaming all classes to TLS to reflect that it's new code which supports currently security standards.
I'd supply ;-) a pull-request if you want.

**Comment by jnthn** [comment]
To be honest I've tended to use the two terms interchangeably when talking about the thing at a high level. :-) We could rename it, especially if it's going to make a better impression on people who know enough about the topic to be bothered/concerned by the name (which, given you created this issue, I guess some folks will). And if we don't take the chance now, it'll be hard to do it without much impact in the future.

Note that it [really is](https://github.com/jnthn/p6-io-socket-async-ssl/blob/master/lib/IO/Socket/Async/SSL.pm6#L290) using the TLS protocols by default. Renaming the IO::Socket::Async::SSL ecosystem module too is more churn than I think I care for, though... :-)

**Comment by abraxxa** [comment]
So does that mean you'd like a patch?
Yes I'm in the network security business and take such things seriously ;-)
What about alias classes for TLS which are recommended in the docs for new code and a soft deprecation for the old ones?

**Comment by jnthn** [comment]
Let's:

1. Create the `cro-tls` repository and push a renamed version of the module there, then get it into the module ecosystem
2. Update everything downstream to use that instead
3. Deprecate Cro::SSL (add `is DEPRECATED` trait) and then remove it a bit later

I've created `cro-tls` and given you push access there, so you won't need to PR that part. :-)

**Comment by abraxxa** [comment]
Pushed a modified cro-ssl to cro-tls.

**Comment by abraxxa** [comment]
Sent pull-requests for cro-http and cro.

**Comment by jnthn** [comment]
Added Cro::TLS to the ecosystem, merged PRs. Thanks, @abraxxa :+1:
