### ISSUE TITLE
Installation hiccups

### ISSUE THREAD

**Issue by scmorrison** [croservices/cro#36]
Hi all, just started tinkering with cro and wanted to make a note about how I got it installed on Debian sid. I am using moar 2017.09, zef v0.1.30. 

Debian package:

1. Install `libssl1.0-dev`

The `zef install --/test cro` required installing specific versions of:

1. JSON::Class v0.0.5
2. JSON::Marshal v0.0.6

I installed those by cloning their respective repos and checkout out the required version, and installing. 

Is there a simpler way to handle the Perl 6 modules versions and get a successful install only using `zef install --/test cro`?

**Comment by jnthn** [comment]
Do you observe this issue with the latest release? These two are most typically pulled in as dependencies of `Test::META6`, which one or more modules in Cro's dependency chain likely uses. (There were also some issues with it in the past where its dependencies were mis-handled, which you may also be observing). If you still see the issue, please could we have a more complete build log? Thanks!

**Comment by scmorrison** [comment]
Thanks, looks like it is successfully installing. I have been testing with the rakudo-star docker image. In case anyone is interested, here are all of the dependencies to install from scratch:

```
apt-get install -y libssl1.0-dev make gcc;                                                                                                                  
zef install Cro --/test;
```

Thanks again.
