### ISSUE TITLE
"Set up your routes" example needs routes

### ISSUE THREAD

**Issue by jbence** [croservices/cro#4]
In the "Set up your routes, and serve them" example on http://mi.cro.services/, the $app variable is created, but not referenced after that. It should probably be passed to the Cro::HTTP::Server.new constructor:

:host\<localhost\>, :port\<10000\>, :application($app);

At least, doing this allowed the example to work OK on Windows 10.

**Comment by Altai-man** [comment]
Thanks!

Fixed in development version, we'll serve updated site as soon as possible.

**Comment by Altai-man** [comment]
Fixed.
