### ISSUE TITLE
cro stub with TLS enabled produces service.p6 with uninterpolated variable

### ISSUE THREAD

**Issue by japhb** [croservices/cro#44]
If you `cro stub` an HTTPS service using cro 0.7.1, the `service.p6` file includes the line:

`certificate-file => %*ENV<{$env-name}_TLS_CERT>`

(Note that `$env-name` did not get properly interpolated into the generated code.)

**Comment by Altai-man** [comment]
Thanks for reporting.

Fixing it now...

**Comment by Altai-man** [comment]
Produces
```
    tls => %(
        private-key-file => %*ENV<YUMEKO_TLS_KEY> ||
            %?RESOURCES<fake-tls/server-key.pem>,
        certificate-file => %*ENV<YUMEKO_TLS_CERT> ||
            %?RESOURCES<fake-tls/server-crt.pem>
    ),
```
now.
