### ISSUE TITLE
cro run, exclude dirs from watch

### ISSUE THREAD

**Issue by scmorrison** [croservices/cro#45]
Is there an option, or planned option, to exclude directories from the `cro run` / `cro trace` file monitoring? For example, it scans `node_modules` and `,precomp`. This slows down startup and when using dynamic `require` causes a `cro` service restart.

**Comment by jnthn** [comment]
There's not an option yet, but yes, this is certainly something that's wanted (I've missed it in the past, just never got around to implementing it yet). I thought that all directories starting with a `.` were already ignored, but we certainly would want this for `node_modules` and similar.

Probably the best way to do it with allowing a list of ignores to be specified in the `.cro.yml`; I already [wrote a module for applying ignores](https://github.com/jnthn/p6-file-ignore) for a previous project that can be re-used for this. :-)

**Comment by scmorrison** [comment]
great to hear, that will definitely come in handy. thanks. Not sure if this is useful, but I noticed it when running `inotifywait -m -r .` before `cro run` that when cro does its scan nothing seems to be modified on disk. Filtering on `-m attrib`, `-m modify`, or `-m close_write` inotifywait returns no output. It's like the access / open / close_nowrite events are triggering the cro restart.

**Comment by jnthn** [comment]
I've specified a way to do this in b12df963b8. @Altai-man please take a look at implementing that; use [this module](https://github.com/jnthn/p6-file-ignore) to do the ignore processing.

**Comment by Altai-man** [comment]
Should be fixed with https://github.com/croservices/cro/commit/291c8c75787cd9ff7c5f6be0326b97a9be78868d
