### ISSUE TITLE
"Set up your routes" example needs an application

### ISSUE THREAD

**Issue by jbence** [croservices/cro#6]
Thank you for addressing #4 quickly; however, the published example does not work:

> Type check failed in binding to parameter '$application'; expected Cro::Transform but got Bool (Bool::True)

Since the example now defines the routes in a variable called $application, the constructor should now read:

> :host\<localhost\>, :port\<10000\>, :application($application);

**Comment by Altai-man** [comment]
Hmm. Copy-pasted code:
```
➜  ~ cat example.pl6 
use Cro::HTTP::Router;
use Cro::HTTP::Server;
my $application = route {
    get -> 'greet', $name {
        content 'text/plain', "Hello, $name!";
    }
}
my Cro::Service $hello = Cro::HTTP::Server.new:
    :host<localhost>, :port<10000>, :$application;
$hello.start;
react whenever signal(SIGINT) { $hello.stop; exit; }
```
then `perl6 example.pl6` and then visiting `http://localhost:10000/greet/Nychts` returns me `Hello, Nychts!`.

`:$var` is a way to express `Pass a named argument with name var and value of $var`.

What rakudo version do you use?

**Comment by jbence** [comment]
> This is Rakudo version 2017.07 built on MoarVM version 2017.07
implementing Perl 6.c.

It's on Windows 10.

**Comment by Altai-man** [comment]
Oh, Windows changes the situation.

Does your variant(`:host<localhost>, :port<10000>, :application($application);`) work for you?

The thing is cro yet to be tested for windows, so the work is to be done in this direction. I afraid we cannot guarantee the work on Windows right now. Maybe @jnthn++ can look closer into your issue, since he works with non-linux systems too, but I cannot promise it will be quickly.

**Comment by jnthn** [comment]
The error is as if the code that was tried was `:application` not `:$application` (which is short for `:application($application)` but a lot less to type). Can't imagine how this would make a difference on Windows, though...maybe something went wrong when it was copied and the $ got dropped, but how it'd drop that one and not all the others beats me.

**Comment by jbence** [comment]
Confirmed: I left out the $, so the example as presented works.
