### ISSUE TITLE
Running tests with CRO_TRACE=1 fails, and without it, hangs

### ISSUE THREAD

**Issue by sjn** [croservices/cro#7]
In the cro git repo, using commit fb251c594c3ed04cd9a16c1b045f4380abb40549:

==========================8<---------------------------------
$ CRO_TRACE=1 zef test .
===> Testing: cro:ver('0.7')
\# Check service up attempt 1: connection refused
\# Check service up attempt 2: connection refused
\# Check service up attempt 3: connection refused
[TRACE(anon 4)] Cro::HTTP::RequestSerializer EMIT Cro::TCP::Message.new(data => Blob[uint8].new(71,69,84,32,47,32,72,84,84,80,47,49,46,49,13,10,72,111,115,116,58,32,108,111,99,97,108,104,111,115,116,13,10,67,111,110,110,101,99,116,105,111,110,58,32,99,108,111,115,101,13,10,13,10), connection => Any)
[TRACE(anon 4)] Cro::TCP::Connector EMIT Cro::TCP::Message.new(data => Buf[uint8].new(72,84,84,80,47,49,46,49,32,50,48,48,32,79,75,13,10,67,111,110,116,101,110,116,45,116,121,112,101,58,32,116,101,120,116,47,112,108,97,105,110,59,32,99,104,97,114,115,101,116,61,117,116,102,45,56,13,10,67,111,110,116,101,110,116,45,108,101,110,103,116,104,58,32,49,50,13,10,13,10), connection => Any)
[TRACE(anon 4)] Cro::HTTP::ResponseParser EMIT Cro::HTTP::Response.new(request => Cro::HTTP::Request, status => 200, body-parser-selector => Cro::HTTP::BodyParserSelector::ResponseDefault, body-serializer-selector => Cro::HTTP::BodySerializerSelector::ResponseDefault, http-version => "1.1", http2-stream-id => Int)
[TRACE(anon 4)] Cro::HTTP::RequestSerializer DONE
[TRACE(anon 4)] Cro::TCP::Connector EMIT Cro::TCP::Message.new(data => Buf[uint8].new(83,101,114,118,105,99,101,32,49,32,79,75), connection => Any)
[TRACE(anon 4)] Cro::TCP::Connector DONE
[TRACE(anon 4)] Cro::HTTP::ResponseParser DONE
\# Failed test 'Got an output message after request'
\# at t/tools-runner.t line 63
\# Actual type: Cro::Tools::Runner::Trace
No such method 'on-stderr' for invocant of type 'Cro::Tools::Runner::Trace'
  in block <unit> at t/tools-runner.t line 64

===> Testing [FAIL]: cro:ver('0.7')
Aborting due to test failure: cro:ver('0.7') (use --force-test to override)
  in code  at /home/sjn/.rakudobrew/moar-nom/install/share/perl6/site/sources/A5C13EF833A22B1E85E78D1CD88BE1B0B0B24DA1 (Zef::Client) line 375
  in method test at /home/sjn/.rakudobrew/moar-nom/install/share/perl6/site/sources/A5C13EF833A22B1E85E78D1CD88BE1B0B0B24DA1 (Zef::Client) line 353
  in sub MAIN at /home/sjn/.rakudobrew/moar-nom/install/share/perl6/site/sources/31FF9E8498781BF95868DF98AD861FCF1211BCC1 (Zef::CLI) line 38
  in block <unit> at /home/sjn/.rakudobrew/moar-nom/install/share/perl6/site/resources/0031ECC6124802A80F7B7B073C50D0A1694E3020 line 1
  in sub MAIN at /home/sjn/.rakudobrew/bin/../moar-nom/install/share/perl6/site/bin/zef line 2
  in block <unit> at /home/sjn/.rakudobrew/bin/../moar-nom/install/share/perl6/site/bin/zef line 2

==============================8<------------------

If I run without CRO_TRACE=1, the tests just hang.

$ perl6 -v
This is Rakudo version 2017.08-42-gf1b086308 built on MoarVM version 2017.08.1-19-g151a25634
implementing Perl 6.c.

**Comment by sjn** [comment]
The output without CRO_TRACE=1 varies, but typically looks something like this:
================================8<--------------
$ zef test .
===> Testing: cro:ver('0.7')
\# Check service up attempt 1: connection refused
\# Check service up attempt 2: connection refused
\# Check service up attempt 3: connection refused
\# Check service up attempt 1: connection refused
\# Check service up attempt 2: connection refused
---------------------------------->8===================

..or with --verbose:

================================8<---------------
$ zef test --verbose .
===> Testing: cro:ver('0.7')
t/tools-crofile.t ... ok
\# Check service up attempt 1: connection refused
--------------------------------------------->8===========================

ping me on #perl6 if you want me to do something :)

**Comment by jnthn** [comment]
Travis also exhibited hangs, which now are gone with latest adjustments.

**Comment by jnthn** [comment]
Haven't seen these hangs in a long while now; please re-open this issue if you see them again.
