### ISSUE TITLE
zef install cro throws - Cannot look up attributes in a IO::Path type object

### ISSUE THREAD

**Issue by indhare** [croservices/cro#72]
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04 LTS
Release:	18.04
Codename:	bionic

Steps used to simulate the problem:

1. Insall Rakudo Perl 6 - https://rakudo.org/files/star/source
2. Install cro - 
$ zef install --/test cro
===> Searching for: cro
===> Updated cpan mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/cpan.json
===> Updated p6c mirror: http://ecosystem-api.p6c.org/projects.json
===> Searching for missing dependencies: IO::Socket::Async::SSL, YAMLish, Cro::WebSocket, Docker::File, File::Ignore
===> Searching for missing dependencies: Cro::HTTP, Base64, Digest::SHA1::Native, Crypt::Random, OpenSSL
===> Searching for missing dependencies: IO::Path::ChildSecure, HTTP::HPACK, Cro::Core, Cro::TLS, JSON::JWT, if
===> Searching for missing dependencies: Digest::HMAC
===> Searching for missing dependencies: Digest
**Cannot look up attributes in a IO::Path type object
  in block  at /home/indhare/rakudo/rakudo-star-2018.04/install/share/perl6/site/sources/3CD130382622E474303EEF475B5E625FC481D071 (Zef::Extract) line 39
  in code  at /home/indhare/rakudo/rakudo-star-2018.04/install/share/perl6/site/sources/7926F4F3ED4C81AA5DA2A54C8AE1E03D03424CCE (Zef::Client) line 260
  in method extract at /home/indhare/rakudo/rakudo-star-2018.04/install/share/perl6/site/sources/7926F4F3ED4C81AA5DA2A54C8AE1E03D03424CCE (Zef::Client) line 244
  in method fetch at /home/indhare/rakudo/rakudo-star-2018.04/install/share/perl6/site/sources/7926F4F3ED4C81AA5DA2A54C8AE1E03D03424CCE (Zef::Client) line 186
  in sub MAIN at /home/indhare/rakudo/rakudo-star-2018.04/install/share/perl6/site/sources/E4784A2A0FA00D16808817186E95FE74BEF3FE2D (Zef::CLI) line 149
  in block <unit> at /home/indhare/rakudo/rakudo-star-2018.04/install/share/perl6/site/resources/3065D08F5332CA244672D7F8A05B603F92BB8A7D line 3
  in sub MAIN at /home/indhare/rakudo/rakudo-star-2018.04/install/share/perl6/site/bin/zef line 2
  in block <unit> at /home/indhare/rakudo/rakudo-star-2018.04/install/share/perl6/site/bin/zef line 2**

**Comment by indhare** [comment]
Sorry for the, false alarm.
Somehow the libssl-dev was not installed after running - # apt-get install build-essential git
after installing libssl-dev the installation of cro succeeded.

$ zef install --/test cro
===> Searching for: cro
===> Updated cpan mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/cpan.json
===> Updated p6c mirror: http://ecosystem-api.p6c.org/projects.json
===> Searching for missing dependencies: IO::Socket::Async::SSL, YAMLish, Cro::WebSocket, Docker::File, File::Ignore
===> Searching for missing dependencies: Cro::HTTP, Base64, Digest::SHA1::Native, Crypt::Random, OpenSSL
===> Searching for missing dependencies: IO::Path::ChildSecure, HTTP::HPACK, Cro::Core, Cro::TLS, JSON::JWT, if
===> Searching for missing dependencies: Digest::HMAC
===> Searching for missing dependencies: Digest
===> Building: Digest::SHA1::Native:ver<0.03>
===> Building [OK] for Digest::SHA1::Native:ver<0.03>
===> Installing: OpenSSL:ver<0.1.19>:auth<github:sergot>
===> Installing: IO::Socket::Async::SSL:ver<0.7.0>
===> Installing: YAMLish:ver<0.0.4>:auth<Leon Timmermans>
===> Installing: IO::Path::ChildSecure:ver<1.001011>
===> Installing: Base64:ver<0.0.1>:auth<github:ugexe>
===> Installing: HTTP::HPACK:ver<0.9.2>
===> Installing: Cro::Core:ver<0.7.6>
===> Installing: Cro::TLS:ver<0.7.6>
===> Installing: if:ver<0.1.0>:auth<github:FROGGS>
===> Installing: Crypt::Random:ver<0.4.1>:auth<github:skinkade>
===> Installing: Digest:ver<0.3.4>:auth<Lucien Grondin>
===> Installing: Digest::HMAC:ver<1.0.0>:auth<github:retupmoca>
===> Installing: JSON::JWT:ver<1.0>:auth<github:retupmoca>
===> Installing: Cro::HTTP:ver<0.7.6.1>
===> Installing: Digest::SHA1::Native:ver<0.03>
===> Installing: Cro::WebSocket:ver<0.7.6>
===> Installing: Docker::File:ver<1.0>:auth<github:jnthn>
===> Installing: File::Ignore
===> Installing: cro:ver<0.7.6>

1 bin/ script [cro] installed to:
/home/indhare/rakudo/rakudo-star-2018.04/install/share/perl6/site/bin

**Comment by Altai-man** [comment]
It looks more like a Zef exception to me, but glad it worked anyway.
The issue can be closed?

**Comment by jnthn** [comment]
Looks like missed dependency and was resolved, so closing. Thanks!
