### ISSUE TITLE
High memory usage for serving static files

### ISSUE THREAD

**Issue by Demayl** [croservices/cro#73]
This example consumes too much RAM ( without freeing it ) every request and sometimes segfaults.
With MVM_SPESH_DISABLE=1 works fine

```bash
ab -c 10 -n 10000 http://127.0.0.1:8888/static/test.txt
```

```perl6
#!/usr/bin/env perl6
use v6.c;
use Cro::HTTP::Server;
use Cro::HTTP::Router;
use Cro::HTTP::Request;

my $routes = route {
    get -> 'static', *@parts {
#        cache-control :public, :max-age(60 * 60); # 1 hour cache for static files
        static 'static/', @parts;
    }   
}   

mkdir 'static';
spurt 'static/test.txt', "A" x 1*1024*1024; # 1 MB txt file

my $service = Cro::HTTP::Server.new: :host('0.0.0.0'), :port(8888), :application($routes);

say "Start " ~ $*PROGRAM-NAME;

$service.start();
react whenever signal(SIGINT) { say "GOT KILL INT.....EXIT"; $service.stop; exit }
```
This is Rakudo version 2018.06-281-g7043559bb built on MoarVM version 2018.06-329-g21ea40f68
implementing Perl 6.c.

**Comment by Altai-man** [comment]
It without SPESH it works fine, it looks to me like rakudo bug rather than Cro::HTTP one.
Thanks for somewhat golfing the example.

**Comment by jnthn** [comment]
Even more interestingly, it seems that it doesn't leak with `MVM_SPESH_INLINE_DISABLE=1` (which means other spesh optimizations, including JIT, are still on).

**Comment by jnthn** [comment]
Tracked it down with massif, and fixed a leak in MoarVM. With that fix, it hits a maximum and then ceases to grow with further requests (threw 50,000 at it, and it didn't budge beyond the point it reached after the first 10,000).
