### ISSUE TITLE
cro is not on PATH

### ISSUE THREAD

**Issue by hkdtam** [croservices/cro#77]
Hi All,

I tried to follow the [Getting started with Cro](https://cro.services/docs/intro/getstarted) guide.  The install was  fine (other than #75 ) and the hello.p6 example produced the expected result.  On the other hand,  `cro stub http hello hello` failed  because `cro` is under
```
/home/david/.rakudobrew/moar-master/install/share/perl6/site/bin
```
I would assume `cro` should, by default, reside under a handy place similar to `zef` which is at
```
/home/david/.rakudobrew/bin/
```
So should I manually add the needful to PATH or is there any good practice to deal with that under rakudobrew?

Thanks in advance for the help.

**Comment by hkdtam** [comment]
Sorry the same happened when I did `zef install p6doc`, perhaps I should raise it to rakudobrew instead.  Thanks anyway.

**Comment by jnthn** [comment]
Ah, forgot to reply to this, but: things get installed to the first writable location available. Often, scripts like `cro` and `p6doc` end up alongside `zef`, so if you have `zef` on path then you'll get the others on path too. I'm guessing whichever installation process you followed ended up with a setup where that isn't the case (or perhaps `zef` was installed with `sudo` or something?)

**Comment by hkdtam** [comment]
Thanks for your feedback, actually that was someone didn't do the needful RTFM. [#132](https://github.com/tadzik/rakudobrew/issues/132).  So for rakudowbrew users, 

`zef install --/test cro && rakudobrew rehash`

should set up everything properly.
