### ISSUE TITLE
ZeroMQ-related warning when stubbing http service without ZeroMQ

### ISSUE THREAD

**Issue by sjn** [croservices/cro#8]
I run this:

$ cro stub http My::Experiment firsttry :websocket

...which produces the following output:

=============================8<------------------------
Stubbing a HTTP Service 'My::Experiment' in 'firsttry'...

WARNING: unhandled Failure detected in DESTROY. If you meant to ignore it, you can mark it as handled by calling .Bool, .so, .not, or .defined methods. The Failure was:
No such symbol 'Cro::Tools::Template::ZeroMQWorkerService'
  in sub get-available-templates at /home/sjn/.rakudobrew/moar-nom/install/share/perl6/site/sources/575A6116019092B74061842AEA0B5B597749E23B (Cro::Tools::TemplateLocator) line 31
  in sub MAIN at /home/sjn/.rakudobrew/moar-nom/install/share/perl6/site/sources/75AA87B0B3D14DE5E701638495D50F0610D7A87C (Cro::Tools::CLI) line 18
  in block <unit> at /home/sjn/.rakudobrew/moar-nom/install/share/perl6/site/resources/DE7784E09AA7C90C649235C72C689A082FAC5189 line 1
  in sub MAIN at /home/sjn/.rakudobrew/bin/../moar-nom/install/share/perl6/site/bin/cro line 2
  in block <unit> at /home/sjn/.rakudobrew/bin/../moar-nom/install/share/perl6/site/bin/cro line 2

WARNING: unhandled Failure detected in DESTROY. If you meant to ignore it, you can mark it as handled by calling .Bool, .so, .not, or .defined methods. The Failure was:
No such symbol 'Cro::Tools::Template::ZeroMQWorkSinkService'
  in sub get-available-templates at /home/sjn/.rakudobrew/moar-nom/install/share/perl6/site/sources/575A6116019092B74061842AEA0B5B597749E23B (Cro::Tools::TemplateLocator) line 31
  in sub MAIN at /home/sjn/.rakudobrew/moar-nom/install/share/perl6/site/sources/75AA87B0B3D14DE5E701638495D50F0610D7A87C (Cro::Tools::CLI) line 18
  in block <unit> at /home/sjn/.rakudobrew/moar-nom/install/share/perl6/site/resources/DE7784E09AA7C90C649235C72C689A082FAC5189 line 1
  in sub MAIN at /home/sjn/.rakudobrew/bin/../moar-nom/install/share/perl6/site/bin/cro line 2
  in block <unit> at /home/sjn/.rakudobrew/bin/../moar-nom/install/share/perl6/site/bin/cro line 2

==============================8<---------------------------------

**Comment by Altai-man** [comment]
Unfortunately, it's a known issue, and likely it's a rakudo bug, not cro bug.

See https://rt.perl.org/Public/Bug/Display.html?id=131996

**Comment by Altai-man** [comment]
Unfortunately, I still have this issue. Like:
```
➜  tester cro stub http first ./first
WARNING: unhandled Failure detected in DESTROY. If you meant to ignore it, you can mark it as handled by calling .Bool, .so, .not, or .defined methods. The Failure was:
No such symbol 'Cro::Tools::Template::ZeroMQWorkSinkService'
  in sub get-available-templates at /home/koto/.rakudobrew/moar-nom/install/share/perl6/site/sources/575A6116019092B74061842AEA0B5B597749E23B (Cro::Tools::TemplateLocator) line 33
  in sub MAIN at /home/koto/.rakudobrew/moar-nom/install/share/perl6/site/sources/75AA87B0B3D14DE5E701638495D50F0610D7A87C (Cro::Tools::CLI) line 18
  in block <unit> at /home/koto/.rakudobrew/moar-nom/install/share/perl6/site/resources/DE7784E09AA7C90C649235C72C689A082FAC5189 line 1
  in sub MAIN at /home/koto/.rakudobrew/moar-nom/install/share/perl6/site/bin/cro line 2
  in block <unit> at /home/koto/.rakudobrew/moar-nom/install/share/perl6/site/bin/cro line 2

Stubbing a HTTP Service 'first' in './first'..
```
or
```
First, please provide a little more information.

Secure (HTTPS) (yes/no) [no]: 
Support HTTP/1.1 (yes/no) [yes]: 
Support HTTP/2.0 (yes/no) [no]: 
Support Web Sockets (yes/no) [no]: 
WARNING: unhandled Failure detected in DESTROY. If you meant to ignore it, you can mark it as handled by calling .Bool, .so, .not, or .defined methods. The Failure was:
No such symbol 'Cro::Tools::Template::ZeroMQWorkerService'
  in sub get-available-templates at /home/koto/.rakudobrew/moar-nom/install/share/perl6/site/sources/575A6116019092B74061842AEA0B5B597749E23B (Cro::Tools::TemplateLocator) line 33
  in sub MAIN at /home/koto/.rakudobrew/moar-nom/install/share/perl6/site/sources/75AA87B0B3D14DE5E701638495D50F0610D7A87C (Cro::Tools::CLI) line 18
  in block <unit> at /home/koto/.rakudobrew/moar-nom/install/share/perl6/site/resources/DE7784E09AA7C90C649235C72C689A082FAC5189 line 1
  in sub MAIN at /home/koto/.rakudobrew/moar-nom/install/share/perl6/site/bin/cro line 2
  in block <unit> at /home/koto/.rakudobrew/moar-nom/install/share/perl6/site/bin/cro line 2
```

I am ahead of master, but above a7d72034b01e2c5ae84169bf86512b8ed483457c commit, so this fix didn't help.

**Comment by jnthn** [comment]
@Altai-man I think I spotted another fix you applied while doing the release notes; can this be closed now?

**Comment by Altai-man** [comment]
@jnthn oh, for sure. It's a workaround suggested by Zoffix, though, but the issue is "gone" as for now.
