### ISSUE TITLE
`put` error super confusing

### ISSUE THREAD

**Issue by chee** [croservices/cro#87]
it took me a while to clock that the reason my debugging `put`s were erroring out with `expected Callable but got Str` was because `put` is an http verb

could the error be more helpful (at least in the case of `put`), like catching the typecheck and printing something like `"one of cro's http verbs were called with "$arg" instead of a handler block in block at sausage.p6 line 69"` ?

**Comment by jnthn** [comment]
Thanks for reporting this. I think we can go one better than improving the error: I've marked the route verbs as `multi`, so now (well, with the next release) a `put` used for debug output will Just Work.
