### ISSUE TITLE
_PORT and _HOST dont seem to work

### ISSUE THREAD

**Issue by hstejas** [croservices/cro#97]
The docker file seem to export `*_PORT` and `*_HOST` to 10000 and localhost but `cro run` seems to pickup 20000 by default, which is rather not consistent.

     $ TESTAPP_PORT=5000 cro run

This doesn't  change the port and the website continues to be served on 20000
similar behaviour with `TESTAPP_HOST` variable

perl6 version 2019.03.1
cro: version 8.1
OS: Ubuntu18.04 and 16.04

**Comment by jnthn** [comment]
`cro run` sets those environment variables, populating them with a port it has picked. That's the intended behavior. If you want to control this yourself but still use `cro run`, then [remove the endpoints entry in .cro.yml](https://cro.services/docs/cro-yml).

**Comment by hstejas** [comment]
Then making the default port same as the ones in example would be consistent, maybe?
